FROM golang:1.25-bookworm

WORKDIR /app


ENV GOPROXY=https://proxy.golang.org,direct


RUN go install github.com/air-verse/air@latest


COPY ./backend/go.mod ./backend/go.sum* ./
RUN go mod download

EXPOSE 8080

# Jalankan Air secara langsung
CMD ["air"]