FROM node:20-bookworm
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install --include=dev
COPY ./frontend . 
ENV NEXT_PRIVATE_LOCAL_SKIP_TURBOPACK=1
RUN npm run build 
EXPOSE 3000
CMD [ "npm", "start" ]
